BaseCommerceSolution/Basecommerce.WebClient.Site/Models/ErrorViewModel.cs
using System;

namespace Basecommerce.WebClient.Site.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BaseCommerceSolution/Basecommerce.WebClient.Site/Models/TokenUserClaimResponse.cs
namespace Basecommerce.WebClient.Site.Models
{
    public class TokenUserClaimResponse
    {
        public string nameid { get; set; }
        public string email { get; set; }
        public string unique_name { get; set; }
        public string family_name { get; set; }
        public int exp { get; set; }
    }
}

BaseCommerceSolution/Basecommerce.WebClient.Site/Controllers/AccountController.cs
using Basecommerce.WebClient.Site.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace Basecommerce.WebClient.Site.Controllers
{
    public class AccountController : Controller
    {
        private readonly string _authenticationWebUrl;

        public AccountController(IConfiguration configuration)
        {
            _authenticationWebUrl = configuration.GetValue<string>("AuthenticationWebUrl");
        }


        [HttpGet]
        public IActionResult Login()
        {
            // Request.Scheme, Request.Host ==> Capture l'url de notre projet.
            // laba : https://localhost:44392/
            // ici : https://localhost:44373/
            return Redirect(_authenticationWebUrl + $"?ReturnBaseUrl={Request.Scheme}://{Request.Host}/");
        }



        [HttpGet]
        public async Task<IActionResult> Connect(string access_token)
        {
            // Notre token est divise en 3 parties par un Point.
            string[] token = access_token.Split('.');
            string value = token[1];
            value = value.PadRight(value.Length + 4 - value.Length % 4, '=');
            var resut = Convert.FromBase64String(value);

            TokenUserClaimResponse user = JsonSerializer.Deserialize<TokenUserClaimResponse>(resut);

            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.nameid),
                new Claim(ClaimTypes.Name, user.unique_name),
                new Claim(ClaimTypes.Email, user.email),
                new Claim("access_token", access_token) // ceci est utlise par apres dans getaway.web.proxy 
            };

            // connection par cookie.
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            // cette cookie dure 10heures.
            AuthenticationProperties authProperties = new AuthenticationProperties
            {
                // doit durer moins que celui du token.
                IssuedUtc = DateTime.UtcNow.AddHours(10)
            };

            //connection
            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

            return Redirect("~/");
        }



        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("~/");
        }

    }
}

BaseCommerceSolution/Basecommerce.WebClient.Site/Controllers/HomeController.cs
using Basecommerce.WebClient.Site.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Basecommerce.WebClient.Site.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BaseCommerceSolution/Basecommerce.WebClient.Site/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Basecommerce.Common;
using Basecommerce.Gateway.Models.Order;
using Basecommerce.Gateway.web.Proxy;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace Basecommerce.WebClient.Site.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class OrdersController : Controller
    {
        private readonly ILogger<OrdersController> _logger;
        private readonly IOrderProxy _orderProxy;

        public int CurrentPage { get; set; } = 1;


        public OrdersController(ILogger<OrdersController> logger, IOrderProxy orderProxy)
        {
            _logger = logger;
            _orderProxy = orderProxy;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var rsukt = await _orderProxy.GetAllAsync(CurrentPage, 10);
            return View(rsukt);
        }


        // GET: Orders/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Orders/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BaseCommerceSolution/Basecommerce.WebClient.Site/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome <b>@User.Identity.Name</b></h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BaseCommerceSolution/Basecommerce.WebClient.Site/Views/Orders/Index.cshtml
@model Basecommerce.Common.DataCollection<Basecommerce.Gateway.Models.Order.OrderDto>

@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">Orders</h1>
    <p>All Orders</p>
</div>

<div class="text-center mt-4 mb-4">
    <a asp-page="/Orders/Create" class="btn btn-primary text-light btn-lg">Create New</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th># Orden</th>
            <th style="width:250px;">Client</th>
            <th style="width:140px;">Type Payment</th>
            <th style="width:100px;">state</th>
            <th style="width:140px;" class="text-right">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    <a href="~/orders/@item.OrderId">@item.OrderNumber</a>
                </td>
                <td>@item.ClientId</td>
                <td>@item.PaymentType</td>
                <td>@item.Status</td>
                <td class="text-right">@item.Total</td>
            </tr>
        }
    </tbody>
</table>

@if (Model.Pages > 1)
{
    <nav>
        <ul class="pagination justify-content-center">
            @for (var index = 1; index <= Model.Pages; index++)
            {
                <li class="page-item @(index == Model.Page ? "active" : "")">
                    <a class="page-link" asp-page="/Orders/Index" asp-route-currentpage="@index">@index</a>
                </li>
            }
        </ul>
    </nav>
}

BaseCommerceSolution/Basecommerce.WebClient.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E-Commerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Basecommerce.WebClient.Site - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>